CREATE TABLE Words(
	id SERIAL PRIMARY KEY,
	english_word VARCHAR(60),
	translate_word VARCHAR(60)
);

create table Users(
	user_id PRIMARY KEY
);

create table Word_user(
	user_id REFERENCES Users(user_id),
	english_word VARCHAR(60),
	translate_word VARCHAR(60)
);

INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Run', 'Бегать');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Red', 'Красный');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Yellow', 'Желтый');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Blue', 'Синий');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Joke', 'Шутка');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Time', 'Время');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Glass', 'Стекло');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('String', 'Строка');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Happy', 'Счастливый');
INSERT INTO WORDS(ENGLISH_WORD, TRANSLATE_WORD) VALUES('Morning', 'Утро');

